---
name: DBIx-Migration
version: 0.06
author:
  - 'Sebastian Riedel, C<sri@oook.de>'
abstract: 'Seamless DB schema up- and downgrades'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Accessor::Fast: 0
  DBI: 0
  File::Slurp: 0
  File::Spec: 0
configure_requires:
  Module::Build: 0.340201
provides:
  DBIx::Migration:
    file: lib/DBIx/Migration.pm
    version: 0.06
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
